// <auto-generated />
using System;
using GameTrip.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameTrip.API.Migrations
{
    [DbContext(typeof(GameTripContext))]
    partial class GameTripContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameTrip.API.Data.AA", b =>
                {
                    b.Property<Guid>("IdAA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AAString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAA");

                    b.ToTable("aa");
                });
#pragma warning restore 612, 618
        }
    }
}
