name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Building Image gametrip-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
                 
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build
        working-directory: ./GameTrip/
        run: dotnet build --configuration Release

      - name: Build Docker Image
        working-directory: ./GameTrip/
        run: docker build --file ./GameTrip.API/Dockerfile --tag dercraker0/gametrip-api:latest ./ --progress=plain --no-cache
      
      - name: Push Docker Image to Registry
        run: docker push dercraker0/gametrip-api:latest
