name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Building Image gametrip-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
                 
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        uses: docker/setup-buildx-action@v1
        with:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./GameTrip/GameTrip.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER}}/gametrip-api:latest
