name: Docker Image CI Staging

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  CI:
    name: Building and deploy Image gametrip-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        working-directory: ./GameTrip/
        run: docker build --file ./GameTrip.API/Dockerfile --tag dercraker0/gametrip-api:staging ./
      
      - name: Push Docker Image to Registry
        run: docker push dercraker0/gametrip-api:staging
